### ISSUE TITLE
Instrument is not turning ON after accepting it

### ISSUE THREAD

**Issue by DaniJarquin** [FranGomezVenegas/TRFE-Components#1]
After creating the instrument, moving it to event and approving it, the instument is still off in the Instrument Control active tab

![Image](https://github.com/FranGomezVenegas/TRFE-Components/assets/143789821/19d7b437-017c-4dac-aa1e-9933ed094109)

http://51.75.202.142:8888/LabPLANET-API/app/procs/InstrumentsAPIqueries?actionName=ACTIVE_INSTRUMENTS_LIST&dbName=demo_v0_9_1&procInstanceName=instruments&finalToken=eyJ1c2VyREIiOiJhZG1pbiIsImRhdGV0aW1lRm9ybWF0QXRQbGF0Zm9ybUxldmVsIjoiRElTQUJMRUQiLCJwcm9jc01vZHVsZU5hbWUiOiJpbnN0cnVtZW50cypJTlNUUlVNRU5UU3xzdG9jaypJTlZFTlRPUllfVFJBQ0tJTkd8bW9uX3dhdGVyKkVOVklST05NRU5UQUxfTU9OSVRPUklOR3xtYl9lbSpFTlZJUk9OTUVOVEFMX01PTklUT1JJTkd8bG90c19yYXcqSU5TUEVDVElPTl9MT1RTX1JBV19NQVQiLCJkYk5hbWUiOiJkZW1vX3YwXzlfMSIsInR5cCI6IkpXVCIsInVzZXJfcHJvY2VkdXJlX2hhc2hjb2RlcyI6Imluc3RydW1lbnRzKjEqMTU5NTM4MDA5NHxzdG9jayoxKi0yMDEwMjQ0MDA1fG1vbl93YXRlcioxKjIwNjMzNjY2OTZ8bWJfZW0qMSoxODU3Njk0NzN8bG90c19yYXcqMSotNTc2NDYxOTc1IiwiZVNpZ24iOiJmaXJtYWRlbW8iLCJ1c2VyREJQYXNzd29yZCI6InRyYXppdDRldmVyIiwidXNlck1haWwiOiJpbmZvQHRyYXppdC5uZXQiLCJ1c2VyX3Byb2NlZHVyZXMiOiJbaW5zdHJ1bWVudHMsIHN0b2NrLCBtb25fd2F0ZXIsIG1iX2VtLCBsb3RzX3Jhd10iLCJhcHBTZXNzaW9uSWQiOiIxODgiLCJhcHBTZXNzaW9uU3RhcnRlZERhdGUiOiJGcmkgU2VwIDAxIDA5OjM4OjUyIFVUQyAyMDIzIiwidXNlclJvbGUiOiJzdXBlcnVzZXIiLCJhbGciOiJIUzI1NiIsImludGVybmFsVXNlcklEIjoiYWRtaW56In0.eyJpc3MiOiJMYWJQTEFORVRkZXN0cmFuZ2lzSW5UaGVOaWdodCJ9.GZdISnTH60W3bNxF6Q34o0GOqaaZCQXkUa5RyThykWA&&isForTesting=true

**Comment by FranGomezVenegas** [comment]
That's correct, even having one event in progress ...the instrument is not decommissioned
